= vagrant-centos7-teamcity
:author: Steve Taylor <Steve.Taylor@taybiz.com>

An example of using vagrant, and some puppet, to spin up a TeamCity box using a CentOS7 machine.

WARNING: This turns down the firewalld service to use the service on http://localhost:18111.

This uses a plugin to keep the virtualbox extension noise/warnings to a minimum
# vagrant plugin install vagrant-vbguest

To use an internal proxy. Handy for caching all the goodness these things use.
# vagrant plugin install vagrant-proxyconf

IMPORTANT: Download a copy of the TeamCity 9.1.3 tar.gz file and place it in the 'provided_packages' folder. Alternatively change the lines in the teamcity.sh file to wget the file directly from the jetbrains site. Your call. My network is a touch slow for that.

Once this spins up ('vagrant up'), you should be able to go to http://localhost:18111 and run through the first start wizard. The data location is preset using a properties file in provisioning/resources. Change it either place. The teamcity.sh script isn't idemponent in that once the "First Start" runs the whole service is present and reprovisioning doesn't do much.

_To change this behaviour maybe dust out the existing install and reinstall everything all over again. Not hard, just not necessary for me just now. But I think soon it will._
